// Mocks generated by Mockito 5.0.15 from annotations
// in resenha/test/app/modules/login/infra/repositories/login_repository_implement_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:resenha/app/modules/login/infra/datasources/login_datasource.dart'
    as _i3;
import 'package:resenha/app/modules/login/infra/models/user_model.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

// ignore: camel_case_types
class _FakeUserModel_0 extends _i1.Fake implements _i2.UserModel {}

/// A class which mocks [LoginDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginDatasource extends _i1.Mock implements _i3.LoginDatasource {
  MockLoginDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserModel> loginGoogle() =>
      (super.noSuchMethod(Invocation.method(#loginGoogle, []),
              returnValue: Future<_i2.UserModel>.value(_FakeUserModel_0()))
          as _i4.Future<_i2.UserModel>);
  @override
  _i4.Future<_i2.UserModel> currentUser() =>
      (super.noSuchMethod(Invocation.method(#currentUser, []),
              returnValue: Future<_i2.UserModel>.value(_FakeUserModel_0()))
          as _i4.Future<_i2.UserModel>);
  @override
  _i4.Future<void> logout() =>
      (super.noSuchMethod(Invocation.method(#logout, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [LoginDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class LoginDataSourceMock extends _i1.Mock implements _i3.LoginDatasource {
  @override
  _i4.Future<_i2.UserModel> loginGoogle() =>
      (super.noSuchMethod(Invocation.method(#loginGoogle, []),
              returnValue: Future<_i2.UserModel>.value(_FakeUserModel_0()))
          as _i4.Future<_i2.UserModel>);
  @override
  _i4.Future<_i2.UserModel> currentUser() =>
      (super.noSuchMethod(Invocation.method(#currentUser, []),
              returnValue: Future<_i2.UserModel>.value(_FakeUserModel_0()))
          as _i4.Future<_i2.UserModel>);
  @override
  _i4.Future<void> logout() =>
      (super.noSuchMethod(Invocation.method(#logout, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  String toString() => super.toString();
}
