include: package:flutter_lints/flutter.yaml
linter:
  rules:
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.mocks.dart"
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
