name: resenha
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  local_auth: ^1.1.6
  flutter_modular: ^3.4.1+1
  mobx: ^2.0.4
  flutter_mobx: ^2.0.2
  google_fonts: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner: ^2.1.1
  mockito: ^5.0.15
  faker: ^2.0.0
  flutter_modular_test: ^1.0.3
  mobx_codegen: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
