// Mocks generated by Mockito 5.0.15 from annotations
// in resenha/test/app/modules/login/infra/services/connectivity_service_implement_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:resenha/app/modules/login/infra/drivers/connectivity_driver.dart'
    as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [ConnectivityDriver].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityDriver extends _i1.Mock
    implements _i2.ConnectivityDriver {
  MockConnectivityDriver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isOnline =>
      (super.noSuchMethod(Invocation.getter(#isOnline),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [ConnectivityDriver].
///
/// See the documentation for Mockito's code generation for more information.
class ConnectivityDriverMock extends _i1.Mock
    implements _i2.ConnectivityDriver {
  @override
  _i3.Future<bool> get isOnline =>
      (super.noSuchMethod(Invocation.getter(#isOnline),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
  @override
  String toString() => super.toString();
}
